### ISSUE TITLE
Java 9 not supported

### ISSUE THREAD

**Issue by wusatosi** [findtheflow/Feedback#24]
```
WARNING: Using incubator modules: jdk.incubator.httpclient
______  _                  
|  ___|| |                 
| |_   | |  ___  __      __
|  _|  | | / _ \ \ \ /\ / /
| |    | || (_) | \ V  V / 
\_|    |_| \___/   \_/\_/  

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Flow Java Agent failed to initialize
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.flow.agent.Agent.premain(Agent.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
Caused by: java.lang.NoClassDefFoundError: java/sql/Timestamp
	at com.flow.shaded.com.fasterxml.jackson.databind.ser.BasicSerializerFactory.<clinit>(BasicSerializerFactory.java:89)
	at com.flow.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:547)
	at com.flow.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:448)
	at com.flow.agent.kafka.KafkaBrokerClient.<clinit>(KafkaBrokerClient.java:20)
	at com.flow.agent.kafka.BrokerClientFactory.create(BrokerClientFactory.java:16)
	at com.flow.agent.Bootstrap.<init>(Bootstrap.java:114)
	at com.flow.agent.Bootstrap.start(Bootstrap.java:60)
	... 11 more`
```
↑log
It seems like java/sql/Timestamp is not visible to Flow because of java 9 module system.

downgrade jdk do help, but I need the new feathers from java 9

Is there anyway to fix it?

**Comment by YoannBuch** [comment]
Thanks for reporting this issue. We don't support java 9 at the moment but we'll look into. I'll keep you updated.

**Comment by yiquanzhou** [comment]
@wusatosi I think a quick fix could be adding `--add-modules java.sql` to the VM options when you run your application with Flow.

**Comment by YoannBuch** [comment]
New version now supports recording applications running with java 9.

See https://plugins.jetbrains.com/plugin/8362-flow/update/44693

**Comment by wusatosi** [comment]
Yes! thank you so much！
