### ISSUE TITLE
Error due starting Flow

### ISSUE THREAD

**Issue by yatsukav** [findtheflow/Feedback#27]
Windows 10

```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

$ java -jar flow-20171022095110.jar
______  _
|  ___|| |
| |_   | |  ___  __      __
|  _|  | | / _ \ \ \ /\ / /
| |    | || (_) | \ V  V /
\_|    |_| \___/   \_/\_/

Flow is starting...

Flow failed to start.
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URI.toURL(Unknown Source)
        at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137)
        at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:77)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:615)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
        at com.flow.ide.environment.EnvironmentServiceImpl.shutdownApplication(EnvironmentServiceImpl.java:116)
        at com.flow.ide.environment.EnvironmentServiceImpl.killRunningApplications(EnvironmentServiceImpl.java:104)
        at com.flow.ide.environment.EnvironmentServiceImpl.startLocalEnvironment(EnvironmentServiceImpl.java:86)
        at com.flow.standalone.EnvironmentLifeCycleManager.onContextRefreshed(EnvironmentLifeCycleManager.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:226)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:143)
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:105)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:387)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.flow.ide.server.JettyWebServer.start(JettyWebServer.java:59)
        at com.flow.standalone.Application.main(Application.java:38)


```

**Comment by yatsukav** [comment]
Maybe the problem in Windows system? I saw next bug with java.net.URI:
_/C:/dir/dir_
And solved with next hack
```
if (SystemUtils.IS_OS_WINDOWS) {
  path = path.substring(1);
}
```

**Comment by YoannBuch** [comment]
Thanks for reporting this issue.

I'm not sure if it's related with Windows as the URI is supposed to be something like "http://localhost:52427".

Can you please send the files located in <USER HOME>/.flow/uris to contact@findtheflow.io? (you can search under C:\Users\USERNAME to find this folder)

The files contain the URIs that led to this exception.

Also you can temporarily fix this issue if you delete the "uris" folder. Let me know if this works for you.

**Comment by YoannBuch** [comment]
Glad to hear!

One of the files was corrupted for some reasons. We'll find a way to better handle such a situation in a feature release. Thanks.
